### ISSUE TITLE
异常，无法绑定后端服务器

### ISSUE THREAD

**Issue by eastNan** [niusmallnan/slb-catalog#1]
# 问题描述
你好请教，阿里云环境，按照这篇文章 https://www.cnrancher.com/rancher-aliyun-slb/ ，尝试  Aliyun-slb服务对接阿里云SLB 碰到了奇怪的问题。

# 测试过程
正常情况，可以绑定后端服务器
slb 80/80(健康检查) -> ecs 80 -> container 80

异常情况，无法绑定后端服务器
slb 80/5080(健康检查) -> ecs 5080 -> container 80

# 异常日志
2018/3/9 下午2:22:40time="2018-03-09T06:22:40Z" level=info msg="LB configs to add: 1"
2018/3/9 下午2:22:40time="2018-03-09T06:22:40Z" level=info msg="Adding LB config: {lb-bp1qlzotiqy7w1sds1uxx web_test2_adminProject_rancher.internal 5080 [{10.139.51.6x 5080}]}"
2018/3/9 下午2:22:40time="2018-03-09T06:22:40Z" level=debug msg="AddLBConfig => config: {lb-bp1qlzotiqy7w1sds1uxx web_test2_adminProject_rancher.internal 5080 [{10.139.51.6x 5080}]}"
2018/3/9 下午2:22:40time="2018-03-09T06:22:40Z" level=debug msg="SLB: lb-bp1qlzotiqy7w1sds1uxx listenerPorts: {[80]}"
2018/3/9 下午2:22:40time="2018-03-09T06:22:40Z" level=debug msg="SLB: lb-bp1qlzotiqy7w1sds1uxx ListenerPortsAndProtocol: {[{80 http}]}"
2018/3/9 下午2:22:40time="2018-03-09T06:22:40Z" level=error msg="Failed to add LB config for endpoint lb-bp1qlzotiqy7w1sds1uxx: SLB 'lb-bp1qlzotiqy7w1sds1uxx' is not configured with instance port matching the service port '5080'"
2018/3/9 下午2:22:40time="2018-03-09T06:22:40Z" level=debug msg="No LB configs to update"

# 小结
目前通过测试来看 SLB的前后端口、健康检查端口 必须一致，否则  Aliyun-slb 无法绑定 阿里云 SLB ，但是这与实际使用环境冲突，以80端口为例每台ECS 主机的 80端是唯一的，一个应用占用后，其他的应用是无法再次绑定 80端口，还请贵司调整。

**Comment by niusmallnan** [comment]
@wchao1241 when you have a chance, please track this issue. we can discuss it later.

**Comment by wchao1241** [comment]
@zongmry 目前SLB只能代理ECS主机端口，所以占用主机端口是正常的
对于“SLB的前后端口、健康检查端口必须一致，否则 Aliyun-slb 无法绑定 阿里云 SLB”这个问题，Aliyun-slb:v0.3.1已经做出修改，前端端口可与后端/健康检查端口不一致

**Comment by eastNan** [comment]
slb:v0.3.1 解决了问题，谢谢。
